### ISSUE TITLE
Update `targetSdkVersion` to 31 for Android 12 Migration 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/AztecEditor-Android#1003]
Parent #https://github.com/wordpress-mobile/WordPress-Android/issues/16062

As part of the migration of WP Android to Android 12, the `targetSdkVersion` on the dependent libraries can be updated to 31. The [Wordpress Android](https://github.com/wordpress-mobile/WordPress-Android) had a `targetSdkVersion` of 30 which now has been updated to 31 in this PR - https://github.com/wordpress-mobile/WordPress-Android/pull/17153. So in order to keep the `targetSdkVersion` to be consistent with the apps, this change needs to be taken up.

**Comment by ParaskP7** [comment]
👋 @AjeshRPai !

As per the discussion on having `targetSdkVersion` updated to `31`, but without updating `compileSdkVersion` to `31` as well (see [here](https://github.com/wordpress-mobile/AztecEditor-Android/pull/982#issuecomment-1291619621)), is it possible that we proceed with updating `compileSdkVersion` from `28` to `31` anytime soon? 🤔 

PS: I am asking that because I needed to test an emoji update on WPAndroid, but couldn't because of the `compileSdkVersion = 28` on Aztec, which propagated some compilation errors that prevented from proceeding further. 😞

**Comment by irfano** [comment]
👋🏻 @ParaskP7!
I plan to finish [updating WPAndorid's `compileSdk` to 33](https://github.com/wordpress-mobile/WordPress-Android/issues/17790) next sprint (I'll be on support rotation next week). Then I will start to update libraries' `compileSdk` to 33. I talked with @AjeshRPai, and I can start with updating the AztecEditor library first . Sounds good or do you need it sooner?

**Comment by ParaskP7** [comment]
👋 @irfano @AjeshRPai !

> I plan to finish https://github.com/wordpress-mobile/WordPress-Android/issues/17790 next sprint (I'll be on support rotation next week).

👍 

> Then I will start to update libraries' compileSdk to 33.

This is great, thanks you both for coordinating and collaborating on this! ❤️ 🙇 🚀 

FYI: With Aztec, I recommend first updating to `compileSdk = 31`, that is, on a separate PR, and then to try and update to `compileSdk = 33`. But, if you think 2 PRs are unnecessary, feel free to jump from `28` to `33` directly, ideally in separate multiple commits. This is just a suggestion as it would have been what I would have done if I were you.

> I talked with @AjeshRPai, and I can start with updating the AztecEditor library first . Sounds good or do you need it sooner?

This sounds good and apologies if this sounded as something "too" urgent. It is just that we need to deal with this `compileSdk = 31` update on Aztec sooner than later and I wouldn't want us to delay that much further. 😊
