### ISSUE TITLE
How to disable visual text editor from editing content

### ISSUE THREAD

**Issue by emunshi** [wordpress-mobile/AztecEditor-Android#736]
is there any method to display content but user should not be able to edit it.

**Comment by hypest** [comment]
👋 @emunshi!

Aztec is subclassing the good old `EditText` Android widget and you can normally set the `isEnabled` property to false to disable editing. And since Aztec is basically 2 editors (visual, html) you can individually enable/disable editing.

I will now close the ticket but feel free to comment. Thanks!
