### ISSUE TITLE
GlideImageLoader implementation build issue

### ISSUE THREAD

**Issue by mustafaberk1996** [wordpress-mobile/AztecEditor-Android#936]
### I followed these steps;

1. Added aztec and glide-loader library in my project
2. And I make  this code ;

```
aztec= Aztec.with(visualEditor, sourceEditor, toolbar, this)
                .addPlugin(galleryButton)
                .setImageGetter(GlideImageLoader(this))
```

then build project i got some error. I share image here.

<img width="1101" alt="Screen Shot 2021-03-11 at 5 41 53 PM" src="https://user-images.githubusercontent.com/57665619/110804297-19d21800-8291-11eb-8784-11e0e72c3fa7.png">

I download github project and build it works well no error, but my project got error.

What should i do to fix this ? any idea ?

**Comment by mchowning** [comment]
:wave: @mustafaberk1996 ! Could you put a sample project showing the error on GitHub? That would make it much easier to diagnose the issue.

**Comment by mustafaberk1996** [comment]
Hi @mchowning the project is [here](https://github.com/mustafaberk1996/aztec-rich-editor). Thanks for your support.

**Comment by mchowning** [comment]
I believe those errors are because you're building your app targeting API level 30, whereas Aztec is still targeting API level 28. Among other things, API level 30 changed some [warnings into errors](https://android-developers.googleblog.com/2020/03/handling-nullability-in-android-11-and.html). In order to build the project targeting API level 30 like you are in your project you will just need to fix those errors. 

I'm sure we'll update this to target the latest api at some point, but it's not a high priority right now so I don't have a timeframe I can give you. If you do make those changes and would be interested in contributing them upstream, we would definitely appreciate it. 🙂

**Comment by mchowning** [comment]
I'm going to go ahead and close this, but feel free to let me know if you run into any other problems.
